### ISSUE TITLE
Options for exact reproducibility

### ISSUE THREAD

**Issue by cookpa** [ftdc-picsl/antsct-aging#1]
@jeffrey-phillips @willtack

For exact reproducibility of results, we would need to:

1. Use single-threaded execution. This incurs a big time penalty for the processing, but is unavoidable due to ITK implementation issues
2. Set ANTS_RANDOM_SEED=something for registration sampling
3. Pass `-u 0` to antsCorticalThickness.sh to disable random sampling in Atropos

Big question of whether it's worth trading bias for variance here. Personally I'm not sure it's worth paying twice as much for a gear run.

More discussion here

https://github.com/ANTsX/ANTs/wiki/antsRegistration-reproducibility-issues#quantification-of-variance-in-registration-results

**Comment by willtack** [comment]
I agree that a huge increase in computational cost is probably not worth avoiding the small reproducibility drop (e.g. mean dice 0.978 doesn't seem prohibitively low to me). Perhaps the default should be multi-threading and/or random sampling, but with a comprehensive `--exact-reproducibility` option that checks all the boxes you mentioned and comes with a conspicuous warning re: computation time in case that is absolutely crucial for some people?

**Comment by cookpa** [comment]
Fixed in ea16b709d3d8a163547b3dbb3a1c77161d4c6b4a
